### ISSUE TITLE
Long table centering

### ISSUE THREAD

**Issue by yvanrichard** [dragonfly-science/dragonfly-latex-templates#27]
longtable environment is not centred properly. It is offset towards the right-hand side of the page.
See encounter-kaikoura/publication

**Comment by katrin-berkenbusch** [comment]
Does this issue correspond with my landscape table busting out of the bottom margin when there's plenty of room at the top of the page?

**Comment by frankmack** [comment]
Added to package, don't think this will resolve @katrin-berkenbusch's issue though.
