### ISSUE TITLE
\url{} in bib file not parsed correctly

### ISSUE THREAD

**Issue by yvanrichard** [dragonfly-science/dragonfly-latex-templates#30]
\emph{} is parsed well in citations, but \url{http://www.iucnredlist.org} is turned into  %5Curl%7Bhttp://www.iucnredlist.org%7D when formatted.

**Comment by frankmack** [comment]
I can't replicate this problem. Is it still an issue?

**Comment by yvanrichard** [comment]
No, it's fine now.
