### ISSUE TITLE
Better support for sideways table

### ISSUE THREAD

**Issue by finlay** [dragonfly-science/dragonfly-latex-templates#35]
Should add a patch to the sideways table environment from the rotating package.

The caption should go over the whole width of the table, at least.

**Comment by frankmack** [comment]
Found a way to make caption span width of sidewaystable. Where should I include this?

**Comment by finlay** [comment]
Awesome!

I would assume you can add it into the 'dtx' file, but perhaps you need to create a new function  as well (still in the dtx file).

**Comment by frankmack** [comment]
Resolved caption width issue using package threeparttable.
