### ISSUE TITLE
reference style

### ISSUE THREAD

**Issue by katrin-berkenbusch** [dragonfly-science/dragonfly-latex-templates#37]
Is there a reason our reference style is so different from the one used for MPI reports?
For example, standard publications have an additional comma, and a comma instead of a colon for the publication source: 
"Eno, N.; MacDonald, D.; Kinnear, J.; Amos, S.; Chapman, C.; Clark, R.; Bunker, F. S. P.; Munro, C. (2001). Effects of crustacean traps on benthic fauna. ICES Journal of Marine Science, 58, 11–20."

Book citations have the number of pages before the publisher details (ideally, they are at the end):
"Bailey, A.; Sorensen, J. (1962). Subantarctic Campbell Island. 305 p. Denver Museum of Natural History, United States."

Chapters and similar publications have the page numbers in parentheses before the publisher or conference details; the "In" should have a colon:
G.F. van Tets (1980). The Campbell Island shag. In Preliminary reports of the
Campbell Island expedition 1975–76. Reserves series no. 7 (pp. 117–119).
Department of Lands and Survey, Wellington.

**Comment by katrin-berkenbusch** [comment]
And websites need to have a full stop at the end.

**Comment by wilkinnikk** [comment]
Hi Katrin,
Just wondering if this is still an issue or has it been resolved over the past year?

**Comment by katrin-berkenbusch** [comment]
Let me check.

**Comment by katrin-berkenbusch** [comment]
I am having problems looking at a recent Dragonfly report. Do you have one?

**Comment by finlay** [comment]
I can't think of one recently, they have all been MPI and other reports.

**Comment by katrin-berkenbusch** [comment]
Caleb’s DeepSpeech report was a Dragonfly one, but it has disappeared. 
;-)

**Comment by finlay** [comment]
Oh, it has moved to Te Hiku Media's new Gorbachev instance

**Comment by katrin-berkenbusch** [comment]
That’s what I thought.

**Comment by finlay** [comment]
[waha-tuhi-project-report.pdf](https://github.com/dragonfly-science/dragonfly-latex-templates/files/3333045/waha-tuhi-project-report.pdf)

**Comment by katrin-berkenbusch** [comment]
Thanks for that @finlay. Looks like some of the internal report issues for references are still relevant.

**Comment by wilkinnikk** [comment]
@katrin-berkenbusch does this look ok now for websites?

[report.pdf](https://github.com/dragonfly-science/dragonfly-latex-templates/files/3336937/report.pdf)

**Comment by wilkinnikk** [comment]
@katrin-berkenbusch, is it alright that the in has now been italicised as well? this aligns with the mpi documents. 
Would you also be able to clarify how "Eno, N.; MacDonald, D.; Kinnear, J.; Amos, S.; Chapman, C.; Clark, R.; Bunker, F. S. P.; Munro, C. (2001). Effects of crustacean traps on benthic fauna. ICES Journal of Marine Science, 58, 11–20." is meant to look?
Am a little confused about what is wrong with it.

**Comment by katrin-berkenbusch** [comment]
Yes, getting there.

Please include colon for “In”, as in: “In: IUCN 2011” and comma at the end: "Gland, Switzerland, IUCN.”.

Gales, N. (2008). Phocarctos hookeri. In IUCN 2011. IUCN red list of threatened species. Retrieved from hĴp://www.iucnredlist.org, 5 November 2011. Gland, Switzerland: IUCN.

Thanks,
Katrin

**Comment by katrin-berkenbusch** [comment]
Hello again,

I don’t think the “in” should be italicised.

For a journal reference, I think the format should be like this:

Eno, N.; MacDonald, D.; Kinnear, J.; Amos, S.; Chapman, C.; Clark, R.; Bunker, F. S. P.; Munro, C. (2001). Effects of crustacean traps on benthic fauna. ICES Journal of Marine Science 58: 11–20.

That is, no comma between the journal title and the volume number, and colon between the volume number and the page numbers.

**Comment by edwardabraham** [comment]
Sorry, for arriving late to this. But the reason that the styles  are different is that the MPI style is ad-hoc. Because of this it is annoying to maintain, and I would prefer to use a standard citation style where we can.  For the dragonfly reports we are  using an APA style. The idea was to stick with that.  We rely on the `biblatex-apa` package (https://ctan.org/pkg/biblatex-apa , with examples here http://mirror.aut.ac.nz/CTAN/macros/latex/contrib/biblatex-contrib/biblatex-apa/biblatex-apa-test.pdf ).

Obviously, where need be we can patch it (as we have been doing). But in general, I think it is better to stick with a standard where we can. The more we diverge from it, the more weird cases that we have to look after.  Looking at your issues,  the APA style does not have fullstops after websites (https://blog.apastyle.org/apastyle/website/ and see this issue https://github.com/plk/biblatex-apa/issues/62), and in the APA style the 'In' is not in italics, and has no colon after it (https://blog.apastyle.org/apastyle/2013/09/how-to-cite-an-anthology-or-collected-works.html).

**Comment by katrin-berkenbusch** [comment]
Yes, sounds good to stick to a standard format (even though it’s annoying). I guess APA is the best one to use?

**Comment by edwardabraham** [comment]
Of course, we did not resist the temptation to tweak, and we can get odd things from having one bib file being used for both APA and MPI styles. Anyways, I hope this finally answers the first question of your issue!!
> Is there a reason our reference style is so different from the one used for MPI reports?

**Comment by katrin-berkenbusch** [comment]
Yes, I think the book citations with page numbers look a bit odd with the page number in the middle.:

Bailey, A.; Sorensen, J. (1962). Subantarctic Campbell Island. 305 p. Denver Museum of Natural History, United States.

I am personally a fan of as little punctuation as possible, but happy to go with a standard format if that’s the easiest way forward.

**Comment by edwardabraham** [comment]
Will leave it to you, just letting you know the history (we already made the *big move* to semi-colons in author lists, which is not standard APA!), and yes they do look odd. I haven't found the bit in the APA style where they talk about page numbers — most examples seem to leave them out.

**Comment by katrin-berkenbusch** [comment]
I think there’s a real advantage in using a standard format…although why did we change to semi-colons? Because we have a comma separating the family name and initials?

**Comment by edwardabraham** [comment]
Not sure why!

**Comment by wilkinnikk** [comment]
After above discussion - have rolled back previous two changes. I have however, removed the parentheses from around the addendum. addendum can be used instead of note in book citations to place the pages at the end of the reference.

**Comment by finlay** [comment]
Bumped version to 1.17
